import type { Metadata } from "next";
import { Suspense } from "react";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import "rc-slider/assets/index.css";
import "bootstrap/dist/css/bootstrap-grid.min.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/FooterNext";
import GlobalFaq from "@/components/GlobalFaq/GlobalFaq";
import AttributionTracker from "@/components/AttributionTracker/AttributionTracker";
import CookieBanner from "@/components/CookieBanner/CookieBanner";
import CarrotQuestScript from "@/components/CarrotQuestScript/CarrotQuestScript";
import SmoothProvider from "@/features/other/SmoothProvider/SmoothProvider";
import "@/scss/app.scss"


export const metadata: Metadata = {
  title: "Ai-UP",
  description: "Generated by create next app",
  verification: {
    yandex: "927769f1682aa02a",
  },
  other: {
    "format-detection": "telephone=no, date=no, email=no, address=no",
  },
};

const yandexMetrikaScript = `
  (function(m,e,t,r,i,k,a){
      m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
      m[i].l=1*new Date();
      for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
      k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
  })(window, document,'script','https://mc.yandex.ru/metrika/tag.js', 'ym');

  ym(97068190, 'init', {webvisor:true, clickmap:true, ecommerce:"dataLayer", referrer: document.referrer, url: location.href, accurateTrackBounce:true, trackLinks:true});
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <script
          id="yandex-metrika-counter"
          dangerouslySetInnerHTML={{ __html: yandexMetrikaScript }}
        />
      </head>
      <body>
        <SmoothProvider header={<Header />}>
          <Suspense fallback={null}>
            <AttributionTracker />
          </Suspense>
          {children}
          <GlobalFaq />
          <Footer />
        </SmoothProvider>
        <CookieBanner />
        <CarrotQuestScript />
        <noscript>
          <div>
            <img
              src="https://mc.yandex.ru/watch/97068190"
              style={{ position: "absolute", left: "-9999px" }}
              alt="Счетчик Яндекс Метрики"
            />
          </div>
        </noscript>
      </body>
    </html>
  );
}
