import type { Metadata } from "next";
import { Suspense } from "react";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import "rc-slider/assets/index.css";
import "bootstrap/dist/css/bootstrap-grid.min.css";
import Footer from "@/components/Footer/FooterNext";
import GlobalFaq from "@/components/GlobalFaq/GlobalFaq";
import AttributionTracker from "@/components/AttributionTracker/AttributionTracker";
import CookieBanner from "@/components/CookieBanner/CookieBanner";
import CarrotQuestScript from "@/components/CarrotQuestScript/CarrotQuestScript";
import HeaderOther from "@/components/HeaderOther/HeaderOther";
import SmoothProvider from "@/features/other/SmoothProvider/SmoothProvider";
import "@/scss/app.scss"


export const metadata: Metadata = {
  title: "Ai-UP",
  description: "Generated by create next app",
  verification: {
    yandex: "927769f1682aa02a",
  },
  other: {
    "format-detection": "telephone=no, date=no, email=no, address=no",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <SmoothProvider header={<HeaderOther />}>
          <Suspense fallback={null}>
            <AttributionTracker />
          </Suspense>
          {children}
          <GlobalFaq />
          <Footer />
        </SmoothProvider>
        <CookieBanner />
        <CarrotQuestScript />
      </body>
    </html>
  );
}
